# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [1]:
%run initialise.py

ModuleNotFoundError: No module named 'mdutils'

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
np.__version__

'1.22.1'

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
l=np.random.randint(1,100,10)
print(l)
print(l.nbytes)
print(l.size)
print(l.itemsize)

[59 46 38 15 24 27 46 87 13 52]
80
10
8


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
np.info("add")

     *** Found in numpy ***
add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added. If ``x1.shape != x2.shape``, they must be broadcastable to a common shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
l=np.zeros(10)
l[4]=1
print(l)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
l=np.random.randint(1,100,10)
print(l)
l[::-1]

[84 35 58 15  5 57 44  5 76 42]


array([42, 76,  5, 44, 57,  5, 15, 58, 35, 84])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
l=np.arange(0,9)
np.reshape(l,(3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
l=[1,2,0,0,4,0]
np.nonzero(l)

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [ ]:
np.reshape(np.random.randint(1,101,27),(3,3,3))

array([[[ 67, 100,  71],
        [  7,  43,  34],
        [ 35,  56,  96]],

       [[ 77,  83,  62],
        [ 44,  90,  83],
        [ 37,  80,  46]],

       [[ 12,  47,  84],
        [ 19,  86,  21],
        [  3,  46,  87]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [ ]:
l=np.random.random((10,10))
#print(l)
(np.min(l),np.max(l))

(0.011802299618826506, 0.9894853190404252)

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [ ]:
np.mean(np.random.random(30))

0.43269340652859595

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
l=np.ones((3,3))
l[1,1]=0
print(l)

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:
#l=np.random.randint(1,100,(1,10))
l1=np.random.randint(1,100,(3,3))
la=np.zeros((3,1))
#print(np.concatenate((l,la),axis=1))
print(np.concatenate((l1,la),axis=1))
#print(l)

[[ 4. 91. 12.  0.]
 [ 8. 42. 28.  0.]
 [12. 16. 79.  0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
np.nan
False  
False
np.nan
True
False

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [ ]:
q = np.eye(5)
for k in range(3):
    np.fill_diagonal(q[k+1:,:],(k+2)%5)
np.fill_diagonal(q[4:,:], 1)
print(q)

[[1. 0. 0. 0. 0.]
 [2. 1. 0. 0. 0.]
 [3. 2. 1. 0. 0.]
 [4. 3. 2. 1. 0.]
 [1. 4. 3. 2. 1.]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
q=np.eye(8)
for k in range(3):
    np.fill_diagonal(q[2*k+2:,:],1)
    np.fill_diagonal(q[:,2*k:],1)
print(q)

[[1. 0. 1. 0. 1. 0. 0. 0.]
 [0. 1. 0. 1. 0. 1. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [ ]:
z=np.random.random((6,7,8))
a=np.reshape(z,6*7*8)
np.where(z==a[99])

#n=np.arange(1,65)
#n[7]=19
#c=np.reshape(n,(4,4,4))
#print(c)
#np.where(c==19)

(array([1]), array([5]), array([3]))

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [ ]:
np.tile([[0,1],[1,0]],(4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [ ]:
l=np.random.randint(1,10,(5,5))
print(l)
l/np.linalg.norm(l)

[[9 6 9 9 2]
 [7 2 1 9 2]
 [8 5 5 4 6]
 [3 7 6 1 4]
 [1 8 8 6 3]]


array([[0.30460385, 0.20306923, 0.30460385, 0.30460385, 0.06768974],
       [0.23691411, 0.06768974, 0.03384487, 0.30460385, 0.06768974],
       [0.27075898, 0.16922436, 0.16922436, 0.13537949, 0.20306923],
       [0.10153462, 0.23691411, 0.20306923, 0.03384487, 0.13537949],
       [0.03384487, 0.27075898, 0.27075898, 0.20306923, 0.10153462]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
a=np.random.randint(1,10,(5,3))
b=np.random.randint(1,10,(3,2))
print(a,b)
np.dot(a,b)

[[9 6 6]
 [9 3 1]
 [8 2 6]
 [7 7 1]
 [9 3 5]] [[9 3]
 [8 1]
 [5 8]]


array([[159,  81],
       [110,  38],
       [118,  74],
       [124,  36],
       [130,  70]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
l=np.random.randint(1,10,7)
print(l)
np.where((l>=3) & (l<=8),-l,l)

[1 3 3 6 2 3 1]


array([ 1, -3, -3, -6,  2, -3,  1])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
9, starts its sum at -1
10, once the module is imported, -1 only means the axis(direction) of the sum

SyntaxError: invalid syntax (1459678622.py, line 1)

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
all excet the last one

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
nan
0
array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)

In [ ]:
l=np.random.randint(1,10,7)+np.random.random(7)
print(l)
np.round(l,0).astype(int)

[2.47215196 3.84815834 4.17747332 6.42462217 3.50446978 2.00356746
 2.44291975]


array([2, 4, 4, 6, 4, 2, 2])

#### 30. How to find common values between two arrays? (★☆☆)

In [ ]:
a=np.random.randint(1,100,(4,4))
b=np.random.randint(1,100,(4,4))
print(a,b)
np.intersect1d(a ,b)

[[21 36 55 96]
 [32 63 94 24]
 [69 86 86 85]
 [68 22  1 95]] [[27 44 19 34]
 [84 10 69 31]
 [79 24 38 35]
 [27 68 57 95]]


array([24, 68, 69, 95])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
np.seterr(all="ignore")

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
No, np.emath.sqrt(-1) is extended to the complex numbers while np.sqrt(-1) is nan...

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [ ]:
print(np.datetime64('today', 'D') - np.timedelta64(1, 'D'))
print(np.datetime64('today', 'D'))
print(np.datetime64('today', 'D') + np.timedelta64(1, 'D'))

2021-12-27
2021-12-28
2021-12-29


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [ ]:
np.arange('2016-07', '20016-08', dtype='datetime64[D]')

array([ '2016-07-01',  '2016-07-02',  '2016-07-03', ..., '20016-07-29',
       '20016-07-30', '20016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [ ]:
 np.add(), np.negative(),  np.divide(), np.multiply()

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [ ]:
l=np.random.random((3,3))+np.random.randint(1,10,(3,3))
print(l)
print(np.floor(l))
print(np.int_(l))
print(l-l%1)
print(np.trunc(l))

[[7.06440068 9.67619543 2.82059953]
 [3.70474807 2.71504565 7.86966394]
 [5.46415653 2.00137089 4.18693016]]
[[7. 9. 2.]
 [3. 2. 7.]
 [5. 2. 4.]]
[[7 9 2]
 [3 2 7]
 [5 2 4]]
[[7. 9. 2.]
 [3. 2. 7.]
 [5. 2. 4.]]
[[7. 9. 2.]
 [3. 2. 7.]
 [5. 2. 4.]]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
np.tile(np.arange(5),(5,1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [ ]:
a=range(1,10)
np.fromiter(a,int)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [ ]:
np.random.randint(1,99,10)/100

array([0.15, 0.94, 0.94, 0.53, 0.42, 0.22, 0.83, 0.3 , 0.91, 0.25])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
l=np.random.random(10)
print(l)
np.sort(l)

[0.75792207 0.42840494 0.03323361 0.34142962 0.80545999 0.35396173
 0.19381687 0.1586691  0.3366541  0.1598303 ]


array([0.03323361, 0.1586691 , 0.1598303 , 0.19381687, 0.3366541 ,
       0.34142962, 0.35396173, 0.42840494, 0.75792207, 0.80545999])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [ ]:
import timeit
x=np.random.randint(1,30,(5,5))
pure_sum = lambda : sum(x)
numpy_sum = lambda : np.sum(x)
t1 = timeit.timeit(pure_sum, number = 1000)
print('Pure Python Sum:', t1)
t2 = timeit.timeit(numpy_sum, number = 1000)
print('Numpy Sum:', t2)
print(x)
p=0
for k in range(10000):
    t1 = timeit.timeit(pure_sum, number = 1000)
    t2 = timeit.timeit(numpy_sum, number = 1000)
    if t1<t2:
        p=p+1
print(p/10000)#percentagem de eficácia de sum sobre np.sum

Pure Python Sum: 0.00500896400626516
Numpy Sum: 0.0047242319997167215
[[15 23 16 21 28]
 [ 9 14 11 12 16]
 [ 1 10 12  5 20]
 [29 27  9 12 11]
 [13 26  6 29 20]]
0.7682


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [ ]:
AA=np.random.randint(1,10,(3,3))
BB=np.random.randint(1,10,(3,3))
#print(AA,BB)
np.all(AA==BB)

False

#### 43. Make an array immutable (read-only) (★★☆)

In [ ]:
a = np.arange(10)
a.flags.writeable = False
#a[0] = 1

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [ ]:
l=np.random.randint(1,10,(10,2))
l1=l[:,:1]+1.j*l[:,1:]
z2polar = lambda z: (abs(z),np.angle(z))
r=np.hstack((z2polar(l1)[0],z2polar(l1)[1]))
print(l)
print(r)

[[7 7]
 [6 1]
 [5 2]
 [4 2]
 [1 8]
 [3 9]
 [8 1]
 [6 4]
 [1 5]
 [9 7]]
[[ 9.89949494  0.78539816]
 [ 6.08276253  0.16514868]
 [ 5.38516481  0.38050638]
 [ 4.47213595  0.46364761]
 [ 8.06225775  1.44644133]
 [ 9.48683298  1.24904577]
 [ 8.06225775  0.12435499]
 [ 7.21110255  0.5880026 ]
 [ 5.09901951  1.37340077]
 [11.40175425  0.66104317]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [ ]:
l=np.random.randint(1,101,10)
print(l)
np.where(l==max(l),0,l)

[66 32 92 40 49 63 43 70 29 51]


array([66, 32,  0, 40, 49, 63, 43, 70, 29, 51])

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [ ]:
n=5
Z = np.zeros((n,n), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,n),np.linspace(0,1,n))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [ ]:
x=np.random.randint(1,100,(2,2))
y=np.random.randint(1,100,(3,2))
xx=np.reshape(x,x.size)
yy=np.reshape(y,y.size)
i=xx.size
j=yy.size
print(x)
#print(np.repeat(xx,j))
print(y)
#print(np.tile(yy,i))
c=np.repeat(xx,j)-np.tile(yy,i)
cf=1/c
#print(c,cf)
np.reshape(cf,(i,j))


[[42 54]
 [20 54]]
[[29 69]
 [91 77]
 [22 80]]


array([[ 0.07692308, -0.03703704, -0.02040816, -0.02857143,  0.05      ,
        -0.02631579],
       [ 0.04      , -0.06666667, -0.02702703, -0.04347826,  0.03125   ,
        -0.03846154],
       [-0.11111111, -0.02040816, -0.01408451, -0.01754386, -0.5       ,
        -0.01666667],
       [ 0.04      , -0.06666667, -0.02702703, -0.04347826,  0.03125   ,
        -0.03846154]])

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

(1+0j)


#### 49. How to print all the values of an array? (★★☆)

In [ ]:
import sys
np.set_printoptions(threshold=sys.maxsize)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [ ]:
l=np.random.randint(1,10000,300000)+np.random.random(300000)
a=np.random.randint(1,10000)
print(l,a)
b=abs(l-a*np.ones(300000))
l[np.argmin(b)]


[8493.59644271 3682.17306169  592.56722032 ... 5335.49475316 4296.87387755
 5424.71459837] 6324


6323.989427713336

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [ ]:
l=np.random.randint(1,10,(5,2))
x,y = np.atleast_2d(l[:,0], l[:,1])
print(l)
print(x)
print(x-x.T)
d = np.sqrt( (x-x.T)**2 + (y-y.T)**2)
print(d)

[[9 8]
 [7 7]
 [4 2]
 [7 4]
 [7 3]]
[[9 7 4 7 7]]
[[ 0 -2 -5 -2 -2]
 [ 2  0 -3  0  0]
 [ 5  3  0  3  3]
 [ 2  0 -3  0  0]
 [ 2  0 -3  0  0]]
[[0.         2.23606798 7.81024968 4.47213595 5.38516481]
 [2.23606798 0.         5.83095189 3.         4.        ]
 [7.81024968 5.83095189 0.         3.60555128 3.16227766]
 [4.47213595 3.         3.60555128 0.         1.        ]
 [5.38516481 4.         3.16227766 1.         0.        ]]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [11]:
a=np.array(np.random.randint(1,10,(3,3))+np.random.random((3,3)),dtype=np.float32)
print(a)
a=a.astype('int32')
print(a)

[[5.1790037 3.515439  6.8316045]
 [9.042453  2.7128096 6.848315 ]
 [1.8200283 5.602951  1.9762886]]
[[5 3 6]
 [9 2 6]
 [1 5 1]]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
from io import StringIO
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


/tmp/ipykernel_967/1015777410.py:8: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  Z = np.genfromtxt(s, delimiter=",", dtype=np.int)


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [15]:
a=np.random.randint(1,10,(3,3))
for i,j in np.ndenumerate(a):
    print(i,j)

(0, 0) 9
(0, 1) 8
(0, 2) 6
(1, 0) 4
(1, 1) 1
(1, 2) 4
(2, 0) 8
(2, 1) 2
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [ ]:
a=np.reshape(np.arange(1,50),(7,7))
p=np.random.randint(-10,-1,13)
pp=np.concatenate((p,np.zeros(7*7-13)))
np.random.shuffle(pp)
pf=np.reshape(pp,(7,7))
#print(a)
#print(pf)
np.where(pf==0,a,pf)

array([[ -5., -10.,  -9.,  -9.,   5.,   6.,   7.],
       [  8.,   9.,  10.,  11.,  12.,  13.,  14.],
       [ 15.,  16.,  17.,  -6.,  19.,  20.,  21.],
       [ -8.,  -2.,  -5.,  25.,  26.,  27.,  28.],
       [ 29.,  30.,  31.,  32.,  33.,  34.,  -6.],
       [ 36.,  37.,  -2.,  39.,  40.,  41.,  42.],
       [ -2.,  44., -10.,  46.,  47.,  48.,  -8.]])

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [ ]:
l=np.random.randint(1,100,(5,5))
j=np.reshape(np.mean(l,axis=1),(5,1))
m=np.tile(j,5)
l-m

array([[ 18.8,  32.8, -29.2,  -4.2, -18.2],
       [ 17.2,  -0.8, -33.8,  18.2,  -0.8],
       [-31.4,  25.6,  12.6,  40.6, -47.4],
       [ 22. , -17. ,  -8. ,  -5. ,   8. ],
       [ 30. , -17. ,  12. , -17. ,  -8. ]])

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

In [20]:
l=np.random.randint(1,20,(2,3,4))+np.random.random((2,3,4))
a=np.random.randint(1,30)
print(l,a)
b=abs(np.reshape(l,2*3*4)-a)
m=min(b)
i=np.where(b==m)
#list(b).index(m)
np.reshape(l,2*3*4)[i]


[[[10.95083557  7.62102483  3.94373246 10.99983705]
  [12.90375667 15.75532676 15.56119652  4.25851293]
  [ 8.94244264 13.42929144  7.26605966  6.38403666]]

 [[15.71868409 16.58541152 14.99197572  7.70983784]
  [ 6.17410987  9.84203868 13.15866363 11.83109908]
  [10.8372392  11.19597763  3.12836042  8.3714033 ]]] 13


array([12.90375667])

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [41]:
a=np.random.random((1,3))
b=np.random.random((3,1))
s=np.zeros(np.shape(a))
for i,j in np.ndenumerate(a):
    s[i]=a[i]+b[i[::-1]]
print(a)
print(b)
print(s)

[[0.79438407 0.21669393 0.72415425]]
[[0.24116777]
 [0.50692953]
 [0.79421213]]
[[1.03555185 0.72362346 1.51836638]]


#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [69]:
n=int(input('comprimento do vetor'))
a=np.random.random(n)
ni=int(input('numero indicies para o 2o vetor'))
pos=np.random.randint(0,np.size(a),4)
num_uns=np.concatenate((np.bincount(pos),np.zeros(np.size(a)-np.size(np.bincount(pos)))))
print(a)
print(pos)
print(num_uns)
print(a+num_uns)

[0.86471318 0.56152071 0.72111733 0.78789028 0.49148479 0.51587255]
[0 2 3 0]
[2. 0. 1. 1. 0. 0.]
[2.86471318 0.56152071 1.72111733 1.78789028 0.49148479 0.51587255]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [90]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

In [ ]:
a=np.random.randint(1,10,(3,3))
b=np.random.randint(1,10,(3,3))
print(a,b)
np.diagonal(np.dot(a,b))

[[8 1 2]
 [8 7 5]
 [1 5 1]] [[5 9 5]
 [4 8 6]
 [7 6 7]]


array([ 58, 158,  42])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [ ]:
a=np.random.randint(1,10,(5,5,3))
b=np.random.randint(1,10,(5,5))
j=np.dot(np.tile(b,(3,1,1)),a)
#print(j)
print(np.shape(j))

(3, 5, 5, 3)


#### 72. How to swap two rows of an array? (★★★)

In [ ]:
a=np.random.randint(1,10,(4,4))
print(a)
a[(0, -1), :] = a[(-1, 0), :]
print(a)

[[6 2 5 6]
 [5 4 4 9]
 [5 4 2 3]
 [5 8 1 2]]
[[5 8 1 2]
 [5 4 4 9]
 [5 4 2 3]
 [6 2 5 6]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [ ]:
a=np.random.randint(1,10,(2,5,2))
p=np.random.randint(1,10,(1,2))
print("ponto p",p)
p0=a[0]
p1=a[1]
v=p0-p1
x=v[:,0]
y=v[:,1]
n=np.sqrt(x**2+y**2)
vv=np.reshape(np.concatenate((np.transpose(x/n),np.transpose(y/n)),axis=0),(5,2),order="F")
v1=p0-np.tile(p,(5,1))
#print(v,np.transpose(x/n),y/n)
print("vetor direçao unitario" ,vv, "vetor hipotenusa",v1)
xx=vv[:,0]*v1[:,0]+vv[:,1]*v1[:,1]
print("projeçao em qtt e sentido ",xx)
hh=np.sqrt(v1[:,0]**2+v1[:,1]**2)
d=np.sqrt(hh**2-xx**2)
print("distancia de p á reta",d)


vetor p [[9 9]]
vetor direçao unitario [[-0.4472136   0.89442719]
 [-0.89442719  0.4472136 ]
 [-0.19611614 -0.98058068]
 [-1.          0.        ]
 [ 0.81373347 -0.58123819]] vetor hipotenusa [[-6 -4]
 [-4 -1]
 [-6 -7]
 [-7 -7]
 [-1 -7]]
projeçao em qtt e sentido  [-0.89442719  3.13049517  8.04076154  7.          3.25493388]
distancia de p á reta [7.15541753 2.68328157 4.51067111 7.         6.27737249]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [ ]:
a=np.random.randint(1,10,(2,5,2)) #5 retas 
p=np.random.randint(1,10,(3,2))   #3 pontos 
#print("ponto/s p",p)
p0=a[0]
p1=a[1]
v=p0-p1 #direção e sentido das retas
x=v[:,0]
y=v[:,1]
n=np.sqrt(x**2+y**2)
vv=np.reshape(np.concatenate((np.transpose(x/n),np.transpose(y/n)),axis=0),(5,2),order="F") #direçao e sentido das retas(Vetor unitário!)
v1=np.tile(p0,(3,1))-np.repeat(p,5,axis=0)

#print(vv) #vetor unitario
#print(p0) #,np.tile(p0,(3,1))
#print(p) #,np.repeat(p,5,axis=0)
#print(v1) #vetor p0 a p (para cada p0 e para cada p...no caso sao 15)

#print(v,np.transpose(x/n),y/n)
#print("vetor direçao unitario" ,vv, "vetor hipotenusa",v1)

vv1=np.tile(vv,(3,1))
#print(vv1)
xx=vv1[:,0]*v1[:,0]+vv1[:,1]*v1[:,1]
#print("projeçao em qtt e sentido ",xx)
hh=np.sqrt(v1[:,0]**2+v1[:,1]**2)
d=np.sqrt(hh**2-xx**2)
print("distancia de p á reta",d)

distancia de p á reta [1.96116135 0.4472136  5.         4.11096096 3.59199652 2.74562589
 0.89442719 6.         5.37587202 3.74817029 2.35339362 2.68328157
 0.         0.31622777 1.56173762]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

In [ ]:
a=np.random.randint(1,10,(3,3))
print(a)
np.linalg.matrix_rank(a)

[[7 8 3]
 [4 5 7]
 [3 3 9]]


3

#### 83. How to find the most frequent value in an array?

In [ ]:
z=np.random.randint(1,30,(7,5,4))
zz=np.reshape(z,7*5*4)
y=np.bincount(zz) #frequências absolutas
print(np.argmax(y)) #np.argmax retorna o indice do maior elemento da array

#ii = np.nonzero(y)[0]
#np.vstack((ii, y[ii])).T

12


array([[ 1,  7],
       [ 2,  1],
       [ 3,  2],
       [ 4,  7],
       [ 5,  4],
       [ 6,  4],
       [ 7,  3],
       [ 8,  8],
       [ 9,  8],
       [10,  8],
       [11,  5],
       [12,  9],
       [13,  5],
       [14,  4],
       [15,  7],
       [16,  5],
       [17,  5],
       [18,  2],
       [19,  5],
       [20,  3],
       [21,  1],
       [22,  4],
       [23,  3],
       [24,  3],
       [25,  8],
       [26,  7],
       [27,  5],
       [28,  7]])

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [ ]:
#irá existir 8*8=64 blocos de 3x3
a=np.random.randint(1,10,(10,10))
print(a) 
from numpy.lib.stride_tricks import as_strided
#as_strided(a, shape=(64,3,3), strides=(40,40,8))

[[8 9 6 8 7 5 1 5 8 9]
 [7 1 6 8 3 7 3 4 3 1]
 [7 9 9 5 4 2 2 4 1 9]
 [9 9 3 7 5 9 8 7 8 3]
 [5 3 7 4 5 2 8 5 1 9]
 [9 4 6 3 2 2 8 4 3 4]
 [2 9 3 8 7 8 1 5 4 3]
 [1 8 9 6 1 9 3 7 7 1]
 [9 1 9 6 1 3 3 5 3 8]
 [2 4 6 3 1 4 1 7 8 2]]


#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [ ]:
z=np.random.randint(1,10,3)
print(z)
print(z**3,z*z*z,np.multiply(z,np.multiply(z,z)))

[3 3 2]
[27 27  8] [27 27  8] [27 27  8]


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [ ]:
a=np.array([[1,1,3],[0,0,0],[3,6,2],[4,4,2],[7,7,7]])
b = a[a.max(axis=1) != a.min(axis=1),:]
print(b)


[[1 1 3]
 [3 6 2]
 [4 4 2]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [ ]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [ ]:
a=np.array([[1,2,3],[3,2,1],[0,0,0],[1,4,3],[3,2,1]])


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)