# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [1]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [5]:
np.__version__

'1.21.5'

#### 3. Create a null vector of size 10 (★☆☆)

In [6]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
l=np.random.randint(1,100,10)
print(l)
l.nbytes

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [7]:
l=np.zeros(10)
l[4]=1
print(l)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [8]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [9]:
l=np.random.randint(1,100,10)
print(l)
l[::-1]

[63 58 31 13 25 54 45 54 17 85]


array([85, 17, 54, 45, 54, 25, 13, 31, 58, 63])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [10]:
l=np.arange(0,9)
np.reshape(l,(3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [11]:
l=[1,2,0,0,4,0]
np.nonzero(l)

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [14]:
np.reshape(np.random.randint(1,101,27),(3,3,3))

array([[[ 88,  74,  58],
        [ 14,  77,  46],
        [ 26,  38,  98]],

       [[ 64,  28,  74],
        [ 83,   8,  44],
        [ 53,   1,  78]],

       [[100,  31,   3],
        [ 23,  24,  75],
        [ 15,  45,  44]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [13]:
l=np.random.random((10,10))
#print(l)
(np.min(l),np.max(l))

(0.011298352474874651, 0.9886175849128707)

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [15]:
np.mean(np.random.random(30))

0.5763287232089005

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [16]:
l=np.ones((3,3))
l[1,1]=0
print(l)

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [17]:
#l=np.random.randint(1,100,(1,10))
l1=np.random.randint(1,100,(3,3))
la=np.zeros((3,1))
#print(np.concatenate((l,la),axis=1))
print(np.concatenate((l1,la),axis=1))
#print(l)

[[14. 11. 78.  0.]
 [63. 12. 81.  0.]
 [27. 79. 69.  0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
np.nan
False  
False
np.nan
True
False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [18]:
q = np.eye(5)
for k in range(3):
    np.fill_diagonal(q[k+1:,:],(k+2)%5)
np.fill_diagonal(q[4:,:], 1)
print(q)

[[1. 0. 0. 0. 0.]
 [2. 1. 0. 0. 0.]
 [3. 2. 1. 0. 0.]
 [4. 3. 2. 1. 0.]
 [1. 4. 3. 2. 1.]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [19]:
q=np.eye(8)
for k in range(3):
    np.fill_diagonal(q[2*k+2:,:],1)
    np.fill_diagonal(q[:,2*k:],1)
print(q)

[[1. 0. 1. 0. 1. 0. 0. 0.]
 [0. 1. 0. 1. 0. 1. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [20]:
z=np.random.random((6,7,8))
a=np.reshape(z,6*7*8)
np.where(z==a[99])

#n=np.arange(1,65)
#n[7]=19
#c=np.reshape(n,(4,4,4))
#print(c)
#np.where(c==19)

(array([1]), array([5]), array([3]))

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [21]:
np.tile([[0,1],[1,0]],(4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [22]:
l=np.random.randint(1,10,(5,5))
print(l)
l/np.linalg.norm(l)

[[9 9 2 1 4]
 [6 9 3 9 6]
 [4 9 9 8 1]
 [2 9 5 7 8]
 [3 3 7 7 5]]


array([[0.28002213, 0.28002213, 0.06222714, 0.03111357, 0.12445428],
       [0.18668142, 0.28002213, 0.09334071, 0.28002213, 0.18668142],
       [0.12445428, 0.28002213, 0.28002213, 0.24890856, 0.03111357],
       [0.06222714, 0.28002213, 0.15556785, 0.21779499, 0.24890856],
       [0.09334071, 0.09334071, 0.21779499, 0.21779499, 0.15556785]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [23]:
a=np.random.randint(1,10,(5,3))
b=np.random.randint(1,10,(3,2))
print(a,b)
np.dot(a,b)

[[4 5 7]
 [1 7 6]
 [8 4 6]
 [7 9 7]
 [6 1 8]] [[7 9]
 [9 7]
 [9 7]]


array([[136, 120],
       [124, 100],
       [146, 142],
       [193, 175],
       [123, 117]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [24]:
l=np.random.randint(1,10,7)
print(l)
np.where((l>=3) & (l<=8),-l,l)

[5 3 6 9 7 5 1]


array([-5, -3, -6,  9, -7, -5,  1])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
9, starts its sum at -1
10, once the module is imported, -1 only means the axis(direction) of the sum

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
all excet the last one

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
nan
0
array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)

In [25]:
l=np.random.randint(1,10,7)+np.random.random(7)
print(l)
np.round(l,0).astype(int)

[2.47215196 3.84815834 4.17747332 6.42462217 3.50446978 2.00356746
 2.44291975]


array([2, 4, 4, 6, 4, 2, 2])

#### 30. How to find common values between two arrays? (★☆☆)

In [26]:
a=np.random.randint(1,100,(4,4))
b=np.random.randint(1,100,(4,4))
print(a,b)
np.intersect1d(a ,b)

[[21 36 55 96]
 [32 63 94 24]
 [69 86 86 85]
 [68 22  1 95]] [[27 44 19 34]
 [84 10 69 31]
 [79 24 38 35]
 [27 68 57 95]]


array([24, 68, 69, 95])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [27]:
np.seterr(all="ignore")

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
No, np.emath.sqrt(-1) is extended to the complex numbers while np.sqrt(-1) is nan...

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [28]:
print(np.datetime64('today', 'D') - np.timedelta64(1, 'D'))
print(np.datetime64('today', 'D'))
print(np.datetime64('today', 'D') + np.timedelta64(1, 'D'))

2021-12-27
2021-12-28
2021-12-29


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [29]:
np.arange('2016-07', '20016-08', dtype='datetime64[D]')

array([ '2016-07-01',  '2016-07-02',  '2016-07-03', ..., '20016-07-29',
       '20016-07-30', '20016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [30]:
l=np.random.random((3,3))+np.random.randint(1,10,(3,3))
print(l)
print(np.floor(l))
print(np.int_(l))
print(l-l%1)
print(np.trunc(l))

[[7.06440068 9.67619543 2.82059953]
 [3.70474807 2.71504565 7.86966394]
 [5.46415653 2.00137089 4.18693016]]
[[7. 9. 2.]
 [3. 2. 7.]
 [5. 2. 4.]]
[[7 9 2]
 [3 2 7]
 [5 2 4]]
[[7. 9. 2.]
 [3. 2. 7.]
 [5. 2. 4.]]
[[7. 9. 2.]
 [3. 2. 7.]
 [5. 2. 4.]]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [31]:
np.tile(np.arange(5),(5,1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [32]:
np.random.randint(1,99,10)/100

array([0.15, 0.94, 0.94, 0.53, 0.42, 0.22, 0.83, 0.3 , 0.91, 0.25])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [33]:
l=np.random.random(10)
print(l)
np.sort(l)

[0.75792207 0.42840494 0.03323361 0.34142962 0.80545999 0.35396173
 0.19381687 0.1586691  0.3366541  0.1598303 ]


array([0.03323361, 0.1586691 , 0.1598303 , 0.19381687, 0.3366541 ,
       0.34142962, 0.35396173, 0.42840494, 0.75792207, 0.80545999])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [34]:
import timeit
x=np.random.randint(1,30,(5,5))
pure_sum = lambda : sum(x)
numpy_sum = lambda : np.sum(x)
t1 = timeit.timeit(pure_sum, number = 1000)
print('Pure Python Sum:', t1)
t2 = timeit.timeit(numpy_sum, number = 1000)
print('Numpy Sum:', t2)
print(x)
p=0
for k in range(10000):
    t1 = timeit.timeit(pure_sum, number = 1000)
    t2 = timeit.timeit(numpy_sum, number = 1000)
    if t1<t2:
        p=p+1
print(p/10000)#percentagem de eficácia de sum sobre np.sum

Pure Python Sum: 0.00500896400626516
Numpy Sum: 0.0047242319997167215
[[15 23 16 21 28]
 [ 9 14 11 12 16]
 [ 1 10 12  5 20]
 [29 27  9 12 11]
 [13 26  6 29 20]]
0.7682


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [35]:
AA=np.random.randint(1,10,(3,3))
BB=np.random.randint(1,10,(3,3))
#print(AA,BB)
np.all(AA==BB)

False

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [53]:
l=np.random.randint(1,10,(10,2))
l1=l[:,:1]+1.j*l[:,1:]
z2polar = lambda z: (abs(z),np.angle(z))
r=np.hstack((z2polar(l1)[0],z2polar(l1)[1]))
print(l)
print(r)

[[7 7]
 [6 1]
 [5 2]
 [4 2]
 [1 8]
 [3 9]
 [8 1]
 [6 4]
 [1 5]
 [9 7]]
[[ 9.89949494  0.78539816]
 [ 6.08276253  0.16514868]
 [ 5.38516481  0.38050638]
 [ 4.47213595  0.46364761]
 [ 8.06225775  1.44644133]
 [ 9.48683298  1.24904577]
 [ 8.06225775  0.12435499]
 [ 7.21110255  0.5880026 ]
 [ 5.09901951  1.37340077]
 [11.40175425  0.66104317]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [38]:
l=np.random.randint(1,101,10)
print(l)
np.where(l==max(l),0,l)

[66 32 92 40 49 63 43 70 29 51]


array([66, 32,  0, 40, 49, 63, 43, 70, 29, 51])

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [42]:
l=np.random.randint(1,10000,300000)+np.random.random(300000)
a=np.random.randint(1,10000)
print(l,a)
b=abs(l-a*np.ones(300000))
m=min(b)
i=list(b).index(m)
l[i]

[9226.22967733 6910.13416335  381.31297384 ... 7894.09223088 8561.04938598
 6894.15349943] 8920


8920.003618493762

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [43]:
l=np.random.randint(1,100,(5,2))
x,y = np.atleast_2d(l[:,0], l[:,1])
print(l)
print(x)
print(x-x.T)
d = np.sqrt( (x-x.T)**2 + (y-y.T)**2)
print(d)

[[95 81]
 [20 55]
 [ 9 70]
 [98 23]
 [37  3]]
[[95 20  9 98 37]]
[[  0 -75 -86   3 -58]
 [ 75   0 -11  78  17]
 [ 86  11   0  89  28]
 [ -3 -78 -89   0 -61]
 [ 58 -17 -28  61   0]]
[[  0.          79.37883849  86.70063437  58.07753438  97.20082304]
 [ 79.37883849   0.          18.60107524  84.30895563  54.70831747]
 [ 86.70063437  18.60107524   0.         100.64790112  72.61542536]
 [ 58.07753438  84.30895563 100.64790112   0.          64.19501538]
 [ 97.20082304  54.70831747  72.61542536  64.19501538   0.        ]]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [44]:
a=np.reshape(np.arange(1,50),(7,7))
p=np.random.randint(-10,-1,13)
pp=np.concatenate((p,np.zeros(7*7-13)))
np.random.shuffle(pp)
pf=np.reshape(pp,(7,7))
#print(a)
#print(pf)
np.where(pf==0,a,pf)

array([[  1.,   2.,   3.,   4.,   5.,   6.,  -8.],
       [  8.,  -2.,  -7.,  -4.,  12.,  -6.,  14.],
       [ 15.,  16.,  17.,  18.,  -8.,  20.,  21.],
       [ 22.,  -9.,  24.,  25.,  26.,  -6.,  28.],
       [ 29.,  -9.,  -7.,  32.,  33.,  -8.,  35.],
       [ 36.,  -9.,  38.,  39.,  40.,  41.,  42.],
       [ 43.,  44.,  45.,  46., -10.,  48.,  49.]])

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [45]:
l=np.random.randint(1,100,(5,5))
j=np.reshape(np.mean(l,axis=1),(5,1))
m=np.tile(j,5)
l-m

array([[ 18.8,  32.8, -29.2,  -4.2, -18.2],
       [ 17.2,  -0.8, -33.8,  18.2,  -0.8],
       [-31.4,  25.6,  12.6,  40.6, -47.4],
       [ 22. , -17. ,  -8. ,  -5. ,   8. ],
       [ 30. , -17. ,  12. , -17. ,  -8. ]])

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

In [46]:
z=np.random.randint(1,30,(7,5,4))
zz=np.reshape(z,7*5*4)
y=np.bincount(zz)
m=max(y)
#ii = np.nonzero(y)[0]
#print(m)
print(list(y).index(m))
#print(y)
#np.vstack((ii, y[ii])).T

8


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)